name: Build Server Docker Image

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code Files
      uses: actions/checkout@v4

    - name: Login to Docker Git
      uses: docker/login-action@v2
      with:
        registry: ${{env.GHCRIO_DOCKER_ADDR}}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_PUBHUB_USER }}
        password: ${{ secrets.DOCKER_PUBHUB_PASS }}
        
    - name: Login to Coding Git
      uses: docker/login-action@v2
      with:
        registry: ${{env.CODING_DOCKER_USER}}
        username: ${{env.CODING_DOCKER_UUID}}
        password: ${{secrets.CODING_DOCKER_PASS}}
    
    - name: Build the Debian 13.00 Server Docker Image
      run: docker buildx build 
           --progress=plain 
           --file ./Dockers/Debian/Desktops/Server 
           --tag pikachuim/debian:13.00-server 
           --build-arg OS_VERSION=trixie 
           --build-arg OS_VERSHOW=13.00 
           --build-arg OS_SYSTEMS=debian 
           ./Dockers/
           
    - name: Build the Debian 12.00 Server Docker Image
      run: docker buildx build 
           --progress=plain 
           --file ./Dockers/Debian/Desktops/Server 
           --tag pikachuim/debian:12.00-server 
           --build-arg OS_VERSION=bookworm
           --build-arg OS_VERSHOW=12.00 
           --build-arg OS_SYSTEMS=debian 
           ./Dockers/
           
    - name: Build the Ubuntu 24.04 Server Docker Image
      run: docker buildx build 
           --progress=plain 
           --file ./Dockers/Ubuntu/Desktops/Server 
           --tag pikachuim/ubuntu:24.04-server 
           --build-arg OS_VERSION=24.04 
           --build-arg OS_VERSHOW=24.04 
           --build-arg OS_SYSTEMS=ubuntu 
           ./Dockers/
      
    - name: Build the Ubuntu 22.04 Server Docker Image
      run: docker buildx build 
           --progress=plain 
           --file ./Dockers/Ubuntu/Desktops/Server 
           --tag pikachuim/ubuntu:22.04-server 
           --build-arg OS_VERSION=22.04 
           --build-arg OS_VERSHOW=22.04 
           --build-arg OS_SYSTEMS=ubuntu 
           ./Dockers/     
           
    - name: Build the Ubuntu 22.04 Server Docker Image
      run:     docker push pikachuim/debian:12.00-server && docker push pikachuim/debian:12.00-server
            && docker push pikachuim/ubuntu:24.04-server && docker push pikachuim/ubuntu:22.04-server
            && docker tag  pikachuim/debian:13.00-server ${{env.CODING_DOCKER_USER}}/open/docker/debian:13.00-server
            && docker push ${{env.CODING_DOCKER_USER}}/open/docker/<PACKAGE>:<VERSION>
            && docker tag  pikachuim/debian:12.00-server ${{env.CODING_DOCKER_USER}}/open/docker/debian:12.00-server
            && docker push ${{env.CODING_DOCKER_USER}}/open/docker/<PACKAGE>:<VERSION>
            && docker tag  pikachuim/ubuntu:24.04-server ${{env.CODING_DOCKER_USER}}/open/docker/ubuntu:24.04-server
            && docker push ${{env.CODING_DOCKER_USER}}/open/docker/<PACKAGE>:<VERSION>
            && docker tag  pikachuim/ubuntu:22.04-server ${{env.CODING_DOCKER_USER}}/open/docker/ubuntu:22.04-server
            && docker push ${{env.CODING_DOCKER_USER}}/open/docker/<PACKAGE>:<VERSION>
            && docker tag  pikachuim/debian:13.00-server ${{env.GHCRIO_DOCKER_ADDR}}/pikachuim/debian:13.00-server
            && docker push ${{env.GHCRIO_DOCKER_ADDR}}/pikachuim/debian:13.00-server
            && docker tag  pikachuim/debian:12.00-server ${{env.GHCRIO_DOCKER_ADDR}}/pikachuim/debian:12.00-server
            && docker push ${{env.GHCRIO_DOCKER_ADDR}}/pikachuim/debian:12.00-server
            && docker tag  pikachuim/ubuntu:24.04-server ${{env.GHCRIO_DOCKER_ADDR}}/pikachuim/ubuntu:24.04-server
            && docker push ${{env.GHCRIO_DOCKER_ADDR}}/pikachuim/ubuntu:24.04-server
            && docker tag  pikachuim/ubuntu:22.04-server ${{env.GHCRIO_DOCKER_ADDR}}/pikachuim/ubuntu:22.04-server
            && docker push ${{env.GHCRIO_DOCKER_ADDR}}/pikachuim/ubuntu:22.04-server
            
