name: Build Desktop Images

on:
  workflow_dispatch:

jobs:
  build-alpine:
    uses: ./.github/workflows/build-alpine.yml
    secrets: inherit

  build-debian:
    uses: ./.github/workflows/build-debian.yml
    secrets: inherit

  build-ubuntu:
    uses: ./.github/workflows/build-ubuntu.yml
    secrets: inherit

  build-fedora:
    uses: ./.github/workflows/build-fedora.yml
    secrets: inherit

  build-archos:
    uses: ./.github/workflows/build-archos.yml
    secrets: inherit
