name: Build All Images

on:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  build-debian:
    uses: ./.github/workflows/build-debian.yml
    secrets: inherit

  build-ubuntu:
    uses: ./.github/workflows/build-ubuntu.yml
    secrets: inherit

  build-alpine:
    uses: ./.github/workflows/build-alpine.yml
    secrets: inherit

  build-fedora:
    uses: ./.github/workflows/build-fedora.yml
    secrets: inherit
