name: Build Debian - nirios

on:
  workflow_call:
  workflow_dispatch:

env:
  IMAGE_PREFIX: pikachuim/debian

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-login
        with:
          username: ${{ secrets.DOCKER_PUBHUB_USER }}
          password: ${{ secrets.DOCKER_PUBHUB_PASS }}
          ghcr_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockers/Debian/Desktops/Nirios
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}:12-nirios
            ${{ env.IMAGE_PREFIX }}:bookworm-nirios
            ghcr.io/${{ env.IMAGE_PREFIX }}:12-nirios
            ghcr.io/${{ env.IMAGE_PREFIX }}:bookworm-nirios
          build-args: |
            OS_VERSION=bookworm
            OS_SYSTEMS=debian
            OS_VERSHOW=12
          cache-from: type=gha
          cache-to: type=gha,mode=max
