name: Build Ubuntu - nirios

on:
  workflow_call:
  workflow_dispatch:

env:
  IMAGE_PREFIX: pikachuim/ubuntu

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['24.04', '26.04']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-login
        with:
          username: ${{ secrets.DOCKER_PUBHUB_USER }}
          password: ${{ secrets.DOCKER_PUBHUB_PASS }}
          ghcr_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockers/Ubuntu/Desktops/Nirios
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}:${{ matrix.version }}-nirios
            ghcr.io/${{ env.IMAGE_PREFIX }}:${{ matrix.version }}-nirios
          build-args: |
            OS_VERSION=${{ matrix.version }}
            OS_SYSTEMS=ubuntu
            OS_VERSHOW=${{ matrix.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
