name: Build All Images

on:
  push:
    branches: [master]
    paths:
      - 'Dockers/**'
      - 'Scripts/**'
  workflow_dispatch:

jobs:
  alpine-server:
    uses: ./.github/workflows/build-alpine-server.yml
    secrets: inherit

  alpine-x11gui:
    needs: [alpine-server]
    uses: ./.github/workflows/build-alpine-x11gui.yml
    secrets: inherit

  alpine-gnome3:
    needs: [alpine-x11gui]
    uses: ./.github/workflows/build-alpine-gnome3.yml
    secrets: inherit

  alpine-xfce4l:
    needs: [alpine-x11gui]
    uses: ./.github/workflows/build-alpine-xfce4l.yml
    secrets: inherit

  alpine-plasma:
    needs: [alpine-x11gui]
    uses: ./.github/workflows/build-alpine-plasma.yml
    secrets: inherit

  debian-server:
    uses: ./.github/workflows/build-debian-server.yml
    secrets: inherit

  debian-x11gui:
    needs: [debian-server]
    uses: ./.github/workflows/build-debian-x11gui.yml
    secrets: inherit

  debian-gnome3:
    needs: [debian-x11gui]
    uses: ./.github/workflows/build-debian-gnome3.yml
    secrets: inherit

  debian-xfce4l:
    needs: [debian-x11gui]
    uses: ./.github/workflows/build-debian-xfce4l.yml
    secrets: inherit

  debian-plasma:
    needs: [debian-x11gui]
    uses: ./.github/workflows/build-debian-plasma.yml
    secrets: inherit

  debian-deepin:
    needs: [debian-x11gui]
    uses: ./.github/workflows/build-debian-deepin.yml
    secrets: inherit

  debian-gxdeos:
    needs: [debian-x11gui]
    uses: ./.github/workflows/build-debian-gxdeos.yml
    secrets: inherit

  debian-nirios:
    needs: [debian-x11gui]
    uses: ./.github/workflows/build-debian-nirios.yml
    secrets: inherit

  debian-lingmo:
    needs: [debian-x11gui]
    uses: ./.github/workflows/build-debian-lingmo.yml
    secrets: inherit

  ubuntu-server:
    uses: ./.github/workflows/build-ubuntu-server.yml
    secrets: inherit

  ubuntu-x11gui:
    needs: [ubuntu-server]
    uses: ./.github/workflows/build-ubuntu-x11gui.yml
    secrets: inherit

  ubuntu-gnome3:
    needs: [ubuntu-x11gui]
    uses: ./.github/workflows/build-ubuntu-gnome3.yml
    secrets: inherit

  ubuntu-xfce4l:
    needs: [ubuntu-x11gui]
    uses: ./.github/workflows/build-ubuntu-xfce4l.yml
    secrets: inherit

  ubuntu-plasma:
    needs: [ubuntu-x11gui]
    uses: ./.github/workflows/build-ubuntu-plasma.yml
    secrets: inherit

  ubuntu-deepin:
    needs: [ubuntu-x11gui]
    uses: ./.github/workflows/build-ubuntu-deepin.yml
    secrets: inherit

  ubuntu-gxdeos:
    needs: [ubuntu-x11gui]
    uses: ./.github/workflows/build-ubuntu-gxdeos.yml
    secrets: inherit

  ubuntu-nirios:
    needs: [ubuntu-x11gui]
    uses: ./.github/workflows/build-ubuntu-nirios.yml
    secrets: inherit

  ubuntu-lingmo:
    needs: [ubuntu-x11gui]
    uses: ./.github/workflows/build-ubuntu-lingmo.yml
    secrets: inherit

  fedora-server:
    uses: ./.github/workflows/build-fedora-server.yml
    secrets: inherit

  fedora-x11gui:
    needs: [fedora-server]
    uses: ./.github/workflows/build-fedora-x11gui.yml
    secrets: inherit

  fedora-gnome3:
    needs: [fedora-x11gui]
    uses: ./.github/workflows/build-fedora-gnome3.yml
    secrets: inherit

  fedora-xfce4l:
    needs: [fedora-x11gui]
    uses: ./.github/workflows/build-fedora-xfce4l.yml
    secrets: inherit

  fedora-plasma:
    needs: [fedora-x11gui]
    uses: ./.github/workflows/build-fedora-plasma.yml
    secrets: inherit

  fedora-deepin:
    needs: [fedora-x11gui]
    uses: ./.github/workflows/build-fedora-deepin.yml
    secrets: inherit

  fedora-lingmo:
    needs: [fedora-x11gui]
    uses: ./.github/workflows/build-fedora-lingmo.yml
    secrets: inherit

  archos-server:
    uses: ./.github/workflows/build-archos-server.yml
    secrets: inherit

  archos-x11gui:
    needs: [archos-server]
    uses: ./.github/workflows/build-archos-x11gui.yml
    secrets: inherit

  archos-gnome3:
    needs: [archos-x11gui]
    uses: ./.github/workflows/build-archos-gnome3.yml
    secrets: inherit

  archos-xfce4l:
    needs: [archos-x11gui]
    uses: ./.github/workflows/build-archos-xfce4l.yml
    secrets: inherit

  archos-plasma:
    needs: [archos-x11gui]
    uses: ./.github/workflows/build-archos-plasma.yml
    secrets: inherit

  archos-deepin:
    needs: [archos-x11gui]
    uses: ./.github/workflows/build-archos-deepin.yml
    secrets: inherit

  archos-cuteos:
    needs: [archos-x11gui]
    uses: ./.github/workflows/build-archos-cuteos.yml
    secrets: inherit
